In [79]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns',None)

In [80]:
df=pd.read_csv("D:\\Numpy\\google_play_project.csv")
print(df)

                      App             Category  Rating  Reviews Size  \
0          Pixel App 3802              FINANCE     4.7   336661  13M
1        Next Editor 9358               DATING     3.0   278556  64M
2         Sketch App 3815            EDUCATION     1.3    54400  44M
3     Master Manager 9993            EDUCATION     1.5   456824  19M
4          Magic Hub 6730               DATING     2.3   137413  91M
...                   ...                  ...     ...      ...  ...
9995    Magic Studio 7027  BOOKS_AND_REFERENCE     3.1    51413   4M
9996      Master App 7662       FOOD_AND_DRINK     2.1   145072  22M
9997     Master Guide 356   HEALTH_AND_FITNESS     3.3   292543  89M
9998    Quick Editor 3457              FINANCE     4.0    34080  75M
9999    Magic Studio 3612         PRODUCTIVITY     2.8   469951  93M

       Installs  Type  Price Content Rating               Genres Last Updated  \
0     10000000+  Free      0     Mature 17+              MEDICAL   04-07-2025
1        10000+  Free      0           Teen               SOCIAL   06-05-2025
2      5000000+  Free      0     Mature 17+            EDUCATION   27-07-2025
3     10000000+  Free      0           Teen                 GAME   20-02-2025
4        10000+  Free      0           Teen  MAPS_AND_NAVIGATION   15-12-2025
...         ...   ...    ...            ...                  ...          ...
9995      1000+  Free      0       Everyone            LIFESTYLE   26-12-2025
9996   1000000+  Free      0       Everyone            EDUCATION   15-10-2025
9997   5000000+  Free      0       Everyone   HEALTH_AND_FITNESS   26-01-2025
9998      1000+  Free      0           Teen   HEALTH_AND_FITNESS   07-02-2025
9999   5000000+  Free      0     Mature 17+               COMICS   04-05-2025

     Current Ver Android Ver
0          3.9.4  4.0 and up
1          3.0.1  4.1 and up
2          1.3.7  4.1 and up
3          2.3.5  5.0 and up
4          4.0.7  4.0 and up
...          ...         ...
9995       4.1.9  6.0 and up
9996       5.5.6  5.0 and up
9997       2.6.4  4.0 and up
9998       4.8.9  5.0 and up
9999       2.8.3  4.0 and up

[10000 rows x 13 columns]

In [81]:
#check total number of apps
df.shape[0]

10000

In [82]:
#check total number of columns
df.shape[1]

13

In [83]:
#display top 5 rows of the dataset
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Pixel App 3802,FINANCE,4.7,336661,13M,10000000+,Free,0,Mature 17+,MEDICAL,04-07-2025,3.9.4,4.0 and up
1,Next Editor 9358,DATING,3.0,278556,64M,10000+,Free,0,Teen,SOCIAL,06-05-2025,3.0.1,4.1 and up
2,Sketch App 3815,EDUCATION,1.3,54400,44M,5000000+,Free,0,Mature 17+,EDUCATION,27-07-2025,1.3.7,4.1 and up
3,Master Manager 9993,EDUCATION,1.5,456824,19M,10000000+,Free,0,Teen,GAME,20-02-2025,2.3.5,5.0 and up
4,Magic Hub 6730,DATING,2.3,137413,91M,10000+,Free,0,Teen,MAPS_AND_NAVIGATION,15-12-2025,4.0.7,4.0 and up

In [84]:
#display last 3 rows of the dataset
df.tail(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9997,Master Guide 356,HEALTH_AND_FITNESS,3.3,292543,89M,5000000+,Free,0,Everyone,HEALTH_AND_FITNESS,26-01-2025,2.6.4,4.0 and up
9998,Quick Editor 3457,FINANCE,4.0,34080,75M,1000+,Free,0,Teen,HEALTH_AND_FITNESS,07-02-2025,4.8.9,5.0 and up
9999,Magic Studio 3612,PRODUCTIVITY,2.8,469951,93M,5000000+,Free,0,Mature 17+,COMICS,04-05-2025,2.8.3,4.0 and up

In [85]:
#Find shape of our dataset(Number of Rows & Number of columns)
df.shape

(10000, 13)

In [86]:
#Get information about our dataset like Total Number Rows, Total Number of Columns, Datatypes of each columns and memory requirements
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10000 non-null  object
 1   Category        10000 non-null  object
 2   Rating          10000 non-null  float64
 3   Reviews         10000 non-null  int64
 4   Size            10000 non-null  object
 5   Installs        10000 non-null  object
 6   Type            10000 non-null  object
 7   Price           10000 non-null  int64
 8   Content Rating  10000 non-null  object
 9   Genres          10000 non-null  object
 10  Last Updated    10000 non-null  object
 11  Current Ver     10000 non-null  object
 12  Android Ver     10000 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 1015.8+ KB

In [87]:
#get overall statistics about the dataframe or get the descriptive statistics about google play store
df.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10000,10000,10000.000000,10000.000000,10000,10000,10000,10000.0,10000,10000,10000,10000,10000
unique,9969,26,NaN,NaN,100,6,1,NaN,3,26,336,500,5
top,Prime Hub 1850,BOOKS_AND_REFERENCE,NaN,NaN,83M,5000000+,Free,NaN,Everyone,DATING,25-05-2025,2.3.6,4.1 and up
freq,2,429,NaN,NaN,127,1694,10000,NaN,3396,429,47,33,2020
mean,NaN,NaN,2.981740,248627.575400,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,1.150797,145074.636481,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,4.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2.000000,121727.500000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,3.000000,248799.500000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.000000,374747.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,499928.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [88]:
#obtain total number of app title contains Lite Maker
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [89]:
df["App"]

0            Pixel App 3802
1          Next Editor 9358
2           Sketch App 3815
3       Master Manager 9993
4            Magic Hub 6730
               ...
9995      Magic Studio 7027
9996        Master App 7662
9997       Master Guide 356
9998      Quick Editor 3457
9999      Magic Studio 3612
Name: App, Length: 10000, dtype: object

In [90]:
df[df["App"].str.contains('Lite Maker',case=False)]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

In [91]:
#find average app rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [92]:
df["Rating"]

0       4.7
1       3.0
2       1.3
3       1.5
4       2.3
       ...
9995    3.1
9996    2.1
9997    3.3
9998    4.0
9999    2.8
Name: Rating, Length: 10000, dtype: float64

In [93]:
df["Rating"].mean()

np.float64(2.9817400000000003)

In [94]:
print("Average app rating =", round(df["Rating"].mean()))

Average app rating = 3

In [95]:
#Find Total Number of Unique Category
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [96]:
df["Category"].nunique()

26

In [101]:
print("Total Number of Unique Category = ",df["Category"].nunique())

Total Number of Unique Category =  26

In [98]:
#Which Category getting the highest average rating?
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [99]:
df['Category']

0                   FINANCE
1                    DATING
2                 EDUCATION
3                 EDUCATION
4                    DATING
               ...
9995    BOOKS_AND_REFERENCE
9996         FOOD_AND_DRINK
9997     HEALTH_AND_FITNESS
9998                FINANCE
9999           PRODUCTIVITY
Name: Category, Length: 10000, dtype: object

In [109]:
df.groupby('Category')['Rating']

In [112]:
df.groupby('Category')['Rating'].mean()

Category
ART_AND_DESIGN         2.978851
BEAUTY                 2.973936
BOOKS_AND_REFERENCE    2.966900
BUSINESS               2.965707
COMICS                 2.995274
COMMUNICATION          2.934715
DATING                 3.024468
EDUCATION              3.014750
ENTERTAINMENT          3.018889
FINANCE                2.922597
FOOD_AND_DRINK         3.009524
GAME                   3.051378
HEALTH_AND_FITNESS     3.029894
LIFESTYLE              2.943309
MAPS_AND_NAVIGATION    3.032741
MEDICAL                2.933508
MUSIC_AND_AUDIO        3.022760
NEWS_AND_MAGAZINES     2.965867
PHOTOGRAPHY            3.021763
PRODUCTIVITY           3.071505
SHOPPING               2.855191
SOCIAL                 2.894920
SPORTS                 2.957377
TOOLS                  2.948072
TRAVEL_AND_LOCAL       2.930628
VIDEO_PLAYERS          3.056728
Name: Rating, dtype: float64

In [113]:
df.groupby('Category')['Rating'].mean().max()

3.071505376344086

In [114]:
df.groupby('Category')['Rating'].mean().nlargest(1)

Category
PRODUCTIVITY    3.071505
Name: Rating, dtype: float64

In [115]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
PRODUCTIVITY           3.071505
VIDEO_PLAYERS          3.056728
GAME                   3.051378
MAPS_AND_NAVIGATION    3.032741
HEALTH_AND_FITNESS     3.029894
DATING                 3.024468
MUSIC_AND_AUDIO        3.022760
PHOTOGRAPHY            3.021763
ENTERTAINMENT          3.018889
EDUCATION              3.014750
FOOD_AND_DRINK         3.009524
COMICS                 2.995274
ART_AND_DESIGN         2.978851
BEAUTY                 2.973936
BOOKS_AND_REFERENCE    2.966900
NEWS_AND_MAGAZINES     2.965867
BUSINESS               2.965707
SPORTS                 2.957377
TOOLS                  2.948072
LIFESTYLE              2.943309
COMMUNICATION          2.934715
MEDICAL                2.933508
TRAVEL_AND_LOCAL       2.930628
FINANCE                2.922597
SOCIAL                 2.894920
SHOPPING               2.855191
Name: Rating, dtype: float64

In [116]:
df.groupby('Category')['Rating'].mean().sort_values().tail(1)

Category
PRODUCTIVITY    3.071505
Name: Rating, dtype: float64

In [118]:
df.groupby('Category')['Rating'].mean().sort_values(ascending=False).head(1)

Category
PRODUCTIVITY    3.071505
Name: Rating, dtype: float64

In [119]:
#Find total number of App having 5 star Rating
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [120]:
df["Rating"]

0       4.7
1       3.0
2       1.3
3       1.5
4       2.3
       ...
9995    3.1
9996    2.1
9997    3.3
9998    4.0
9999    2.8
Name: Rating, Length: 10000, dtype: float64

In [124]:
df[df['Rating'] == 5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
50,Smart Maker 8528,MEDICAL,5.0,461580,4M,5000000+,Free,0,Mature 17+,ENTERTAINMENT,12-01-2025,3.0.6,4.0 and up
91,Quick Guide 7258,HEALTH_AND_FITNESS,5.0,153808,3M,5000000+,Free,0,Mature 17+,HEALTH_AND_FITNESS,01-05-2025,2.3.3,4.0 and up
136,Creative App 9690,HEALTH_AND_FITNESS,5.0,164905,53M,100000+,Free,0,Teen,DATING,06-10-2025,5.3.4,6.0 and up
210,Smart Tracker 1751,MEDICAL,5.0,390213,55M,10000000+,Free,0,Teen,LIFESTYLE,26-03-2025,2.4.4,6.0 and up
369,Master App 533,COMMUNICATION,5.0,67297,80M,5000000+,Free,0,Mature 17+,LIFESTYLE,24-08-2025,4.6.4,6.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9713,Easy Player 2823,ENTERTAINMENT,5.0,479312,19M,100000+,Free,0,Teen,SOCIAL,18-07-2025,1.8.5,4.0 and up
9720,Go Plus 3678,LIFESTYLE,5.0,270588,53M,1000000+,Free,0,Teen,TOOLS,27-02-2025,4.2.2,4.2 and up
9874,Digital Tracker 6554,COMICS,5.0,113203,19M,100000+,Free,0,Mature 17+,COMICS,03-10-2025,1.2.3,4.0 and up
9944,Pixel Connect 8697,FOOD_AND_DRINK,5.0,205751,67M,100000+,Free,0,Teen,COMICS,23-06-2025,4.4.4,4.1 and up
9965,Master Editor 2082,TOOLS,5.0,81808,33M,10000000+,Free,0,Mature 17+,DATING,24-08-2025,2.6.9,6.0 and up

In [133]:
print("total number of App having 5 star Rating = ",len(df[df['Rating'] == 5]))

total number of App having 5 star Rating =  131

In [135]:
print("total number of App having 5 star Rating = ",df[df['Rating'] == 5].shape[0])

total number of App having 5 star Rating =  131

In [136]:
print("total number of App having 5 star Rating = ",df[df['Rating'] == 5].count().unique()[0])

total number of App having 5 star Rating =  131

In [137]:
#Find average values of reviews
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [138]:
df['Reviews']

0       336661
1       278556
2        54400
3       456824
4       137413
         ...
9995     51413
9996    145072
9997    292543
9998     34080
9999    469951
Name: Reviews, Length: 10000, dtype: int64

In [141]:
df['Reviews'].dtype

dtype('int64')

In [142]:
df['Reviews'].astype("float")

0       336661.0
1       278556.0
2        54400.0
3       456824.0
4       137413.0
          ...
9995     51413.0
9996    145072.0
9997    292543.0
9998     34080.0
9999    469951.0
Name: Reviews, Length: 10000, dtype: float64

In [145]:
print("Average values of reviews = ",df['Reviews'].mean())

Average values of reviews =  248627.5754

In [146]:
#Find total number of free and paid apps
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [156]:
df[df['Type']=='Free'].value_counts()

App                 Category             Rating  Reviews  Size  Installs   Type  Price  Content Rating  Genres               Last Updated  Current Ver  Android Ver
Color App 1129      TRAVEL_AND_LOCAL     2.2     447413   56M   5000000+   Free  0      Mature 17+      COMICS               17-07-2025    5.9.6        6.0 and up     1
Pro App 1791        SOCIAL               3.4     140404   18M   5000000+   Free  0      Teen            VIDEO_PLAYERS        15-06-2025    4.4.3        6.0 and up     1
Prime Tracker 9284  NEWS_AND_MAGAZINES   4.8     438565   80M   1000+      Free  0      Everyone        SHOPPING             02-11-2025    1.8.0        4.2 and up     1
Prime Tracker 9468  FOOD_AND_DRINK       2.8     160852   69M   100000+    Free  0      Teen            ART_AND_DESIGN       15-02-2025    2.8.8        5.0 and up     1
Prime Tracker 9541  DATING               2.8     126113   87M   10000000+  Free  0      Teen            SPORTS               10-02-2025    3.4.1        4.2 and up     1
                                                                                                                                                                      ..
Go Tracker 5338     MEDICAL              3.6     266052   13M   1000+      Free  0      Everyone        PRODUCTIVITY         24-05-2025    1.6.1        6.0 and up     1
Go Tracker 601      BEAUTY               2.5     1199     61M   10000+     Free  0      Everyone        MAPS_AND_NAVIGATION  22-04-2025    4.7.7        6.0 and up     1
Go Tracker 6522     HEALTH_AND_FITNESS   4.8     96019    28M   100000+    Free  0      Everyone        SPORTS               27-01-2025    2.3.2        4.2 and up     1
Go Tracker 6810     BOOKS_AND_REFERENCE  1.0     379834   12M   1000+      Free  0      Teen            PHOTOGRAPHY          10-02-2025    3.6.9        6.0 and up     1
Ultra Tracker 9967  NEWS_AND_MAGAZINES   4.8     338966   2M    5000000+   Free  0      Teen            DATING               16-05-2025    4.4.7        4.0 and up     1
Name: count, Length: 10000, dtype: int64

In [160]:
s=df['Type'].value_counts()

In [164]:
print('total number of free apps = ',s['Free'])

total number of free apps =  10000

In [165]:
#Which App has maximum reviews?
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [166]:
df['Reviews']

0       336661
1       278556
2        54400
3       456824
4       137413
         ...
9995     51413
9996    145072
9997    292543
9998     34080
9999    469951
Name: Reviews, Length: 10000, dtype: int64

In [170]:
df['Reviews'].max()

499928

In [172]:
df[df['Reviews'] == df['Reviews'].max()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5727,Digital Player 4280,TOOLS,3.7,499928,17M,10000000+,Free,0,Teen,ENTERTAINMENT,06-08-2025,5.7.7,4.2 and up

In [173]:
df[df['Reviews'] == df['Reviews'].max()]['App']

5727    Digital Player 4280
Name: App, dtype: object

In [174]:
type(df[df['Reviews'] == df['Reviews'].max()]['App'])

pandas.core.series.Series

In [175]:
print("App has maximum reviews = ",df[df['Reviews'] == df['Reviews'].max()]['App'][5727])

App has maximum reviews =  Digital Player 4280

In [176]:
#Display top 5 apps having highest reviews?
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [178]:
df['Reviews']

0       336661
1       278556
2        54400
3       456824
4       137413
         ...
9995     51413
9996    145072
9997    292543
9998     34080
9999    469951
Name: Reviews, Length: 10000, dtype: int64

In [180]:
df['Reviews'].sort_values(ascending = False).head(5)

5727    499928
8641    499862
3389    499848
4565    499824
5648    499820
Name: Reviews, dtype: int64

In [182]:
indices = df['Reviews'].sort_values(ascending = False).head(5).index

In [183]:
print(indices)

Index([5727, 8641, 3389, 4565, 5648], dtype='int64')

In [184]:
df.iloc[indices]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5727,Digital Player 4280,TOOLS,3.7,499928,17M,10000000+,Free,0,Teen,ENTERTAINMENT,06-08-2025,5.7.7,4.2 and up
8641,Master App 867,SOCIAL,3.4,499862,11M,1000000+,Free,0,Teen,TOOLS,05-03-2025,5.3.9,5.0 and up
3389,Prime Manager 4545,BOOKS_AND_REFERENCE,3.2,499848,54M,10000+,Free,0,Mature 17+,BEAUTY,18-11-2025,4.6.8,6.0 and up
4565,Master Tool 4401,NEWS_AND_MAGAZINES,4.0,499824,8M,100000+,Free,0,Everyone,SOCIAL,20-05-2025,5.6.9,4.2 and up
5648,Digital Player 4674,COMICS,4.9,499820,86M,10000+,Free,0,Everyone,COMMUNICATION,01-04-2025,3.9.7,4.2 and up

In [185]:
df.iloc[indices]['App']

5727    Digital Player 4280
8641         Master App 867
3389     Prime Manager 4545
4565       Master Tool 4401
5648    Digital Player 4674
Name: App, dtype: object

In [187]:
df.iloc[indices]['App'].value_counts()

App
Digital Player 4280    1
Master App 867         1
Prime Manager 4545     1
Master Tool 4401       1
Digital Player 4674    1
Name: count, dtype: int64

In [188]:
#Find the average Rating of free apps?
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [189]:
df['Rating']

0       4.7
1       3.0
2       1.3
3       1.5
4       2.3
       ...
9995    3.1
9996    2.1
9997    3.3
9998    4.0
9999    2.8
Name: Rating, Length: 10000, dtype: float64

In [192]:
df.groupby('Type')['Rating'].mean()

Type
Free    2.98174
Name: Rating, dtype: float64

In [197]:
df.groupby('Type')['Rating'].agg(["mean"])

         mean
Type
Free  2.98174

In [201]:
print("The average Rating of free apps = ",df.groupby('Type')['Rating'].agg(["mean"]))

The average Rating of free apps =           mean
Type
Free  2.98174

In [202]:
#Display Top 5 having maximum installs
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [203]:
df["Installs"]

0       10000000+
1          10000+
2        5000000+
3       10000000+
4          10000+
          ...
9995        1000+
9996     1000000+
9997     5000000+
9998        1000+
9999     5000000+
Name: Installs, Length: 10000, dtype: object

In [204]:
type(df["Installs"])

pandas.core.series.Series

In [205]:
df["Installs"].dtype

dtype('O')

In [207]:
df["Installs-1"] = df["Installs"].str.replace(",","")

In [208]:
df["Installs-1"]

0       10000000+
1          10000+
2        5000000+
3       10000000+
4          10000+
          ...
9995        1000+
9996     1000000+
9997     5000000+
9998        1000+
9999     5000000+
Name: Installs-1, Length: 10000, dtype: object

In [211]:
df["Installs-1"] = df["Installs-1"].str.replace("+","")

In [212]:
df["Installs-1"]

0       10000000
1          10000
2        5000000
3       10000000
4          10000
          ...
9995        1000
9996     1000000
9997     5000000
9998        1000
9999     5000000
Name: Installs-1, Length: 10000, dtype: object

In [214]:
#convert dtype of df[Intaslls-1] into int type
df['Installs-1'] = df["Installs-1"].astype("int")

In [216]:
df["Installs-1"]

0       10000000
1          10000
2        5000000
3       10000000
4          10000
          ...
9995        1000
9996     1000000
9997     5000000
9998        1000
9999     5000000
Name: Installs-1, Length: 10000, dtype: int64

In [218]:
df["Installs-1"].sort_values(ascending=False).head(5)

0       10000000
5978    10000000
5894    10000000
1673    10000000
1672    10000000
Name: Installs-1, dtype: int64

In [223]:
indices = df["Installs-1"].sort_values(ascending=False).head().index
df.iloc[indices]['App']

0         Pixel App 3802
5978      Magic Hub 2213
5894    Pixel Maker 1526
1673    Easy Player 3407
1672    Magic Guide 3061
Name: App, dtype: object